apiVersion: apps/v1
kind: Deployment
metadata:
  name: producer
  namespace: mensageria
spec:
  replicas: 1

  selector:
    matchLabels:
      app: producer

  template:
    metadata:
      labels:
        app: producer

    spec:
      containers:
        - name: producer
          image: speedowagon/mensageria-producer:1.0

          env:
            - name: RABBITMQ_HOST
              value: "rabbitmq"

            - name: QUEUE
              value: "fila_teste"

            - name: RATE
              value: "100"
