apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
  namespace: mensageria
spec:
  replicas: 1

  selector:
    matchLabels:
      app: worker

  template:
    metadata:
      labels:
        app: worker

    spec:
      containers:
        - name: worker
          image: mensageria-worker:1.0
          imagePullPolicy: Never

          env:
            - name: RABBITMQ_HOST
              value: "rabbitmq"

            - name: QUEUE
              value: "fila_teste"

            - name: PROCESS_TIME
              value: "0.05"
